name: Compile Z9Pay Mobile App Packages
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android Packages
        run: |
          cd android
          chmod +x gradlew
          # Assemble APK for testing
          ./gradlew assembleDebug
          # Bundle AAB for Google Play Store release
          ./gradlew bundleRelease

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: Z9Pay-Binaries
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/bundle/release/app-release.aab