name: Compile Z9Pay Mobile App Packages
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install and Build
        run: |
          npm install
          # Explicitly install the CLI to ensure it is available in PATH
          npm install -g @capacitor/cli
          # Sync to generate the android folder
          npx cap sync android
          
      - name: Compile Android
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: Z9Pay-Build
          path: android/app/build/outputs/apk/debug/app-debug.apk
          android/app/build/outputs/bundle/release/app-release.aab